### PR TITLE
Base model interfaces

### PR DESCRIPTION
**Pull request by MeltingShoe**
Just wrote some interfaces for FF, train, and perform action with ABC. They only require that subclasses overwrite the function they're made for. I haven't touched the FF, train, or PA classes for the cifar10 example yet, I'm just making this pull request to make sure this is how you guys think the interfaces should be implemented before I do more work and I'm not completely missing something.

### CODE REVIEW

**Comment by MeltingShoe** [comment]
[Feed forward interface](https://trello.com/c/aWf89PFn/6-feed-forward-interface)

**Comment by MeltingShoe** [comment]
[Train interface](https://trello.com/c/PvuZLW4P/7-train-interface)

**Comment by MeltingShoe** [comment]
[Perform action interface](https://trello.com/c/dfE0t2ZY/8-perform-action-interface)

**Comment by cece95** [comment]
I think we are good to go, we can just modify them later if we absolutely need to

**Pull request merged**
